In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/car.csv'
data = pd.read_csv(file_url)  



In [2]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [3]:
data.info() #4개의 숫자형 변수, 9개의 object 변수 확인 가능 
# 또한 mileage, engine, max_power, torque, seats null값 존재 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [4]:
# engine 변수 전처리

data['engine'].str.split()

0       [1248, CC]
1       [1498, CC]
2       [1497, CC]
3       [1396, CC]
4       [1298, CC]
           ...    
8123    [1197, CC]
8124    [1493, CC]
8125    [1248, CC]
8126    [1396, CC]
8127    [1396, CC]
Name: engine, Length: 8128, dtype: object

In [5]:
data['engine'].str.split('8')

0       [124,  CC]
1       [149,  CC]
2        [1497 CC]
3        [1396 CC]
4       [129,  CC]
           ...    
8123     [1197 CC]
8124     [1493 CC]
8125    [124,  CC]
8126     [1396 CC]
8127     [1396 CC]
Name: engine, Length: 8128, dtype: object

In [6]:
data['engine'].str.split(expand=True) # 공백 기준으로 문자를 분할하여 별도의 변수로 출력

0   1
0     1248  CC
1     1498  CC
2     1497  CC
3     1396  CC
4     1298  CC
...    ...  ..
8123  1197  CC
8124  1493  CC
8125  1248  CC
8126  1396  CC
8127  1396  CC

[8128 rows x 2 columns]

In [7]:
data[['engine','engine_unit']]= data['engine'].str.split(expand=True) #분할된 문자들을 새로운 변수들(engine, engine_unit)로 저장

In [8]:
data['engine'].head()

0    1248
1    1498
2    1497
3    1396
4    1298
Name: engine, dtype: object

In [9]:
data['engine'].unique() # 고윳값 확인

array(['1248', '1498', '1497', '1396', '1298', '1197', '1061', '796',
       '1364', '1399', '1461', '993', nan, '1198', '1199', '998', '1591',
       '2179', '1368', '2982', '2494', '2143', '2477', '1462', '2755',
       '1968', '1798', '1196', '1373', '1598', '1998', '1086', '1194',
       '1172', '1405', '1582', '999', '2487', '1999', '3604', '2987',
       '1995', '1451', '1969', '2967', '2497', '1797', '1991', '2362',
       '1493', '1599', '1341', '1794', '799', '1193', '2696', '1495',
       '1186', '1047', '2498', '2956', '2523', '1120', '624', '1496',
       '1984', '2354', '814', '793', '1799', '936', '1956', '1997',
       '1499', '1948', '2997', '2489', '2499', '2609', '2953', '1150',
       '1994', '1388', '1527', '2199', '995', '2993', '1586', '1390',
       '909', '2393', '3198', '1339', '2835', '2092', '1595', '2496',
       '1596', '1597', '2596', '2148', '1299', '1590', '2231', '2694',
       '2200', '1795', '1896', '1796', '1422', '1489', '2359', '2197',
       '2999

In [10]:
data.drop('engine_unit', axis=1,inplace= True)

In [11]:
# max_power 변수 전처리
data[['max_power', 'max_power_unit']] = data['max_power'].str.split(expand=True) #분할된 문자들을 새로운 변수들로 저장

In [12]:
data['max_power'].head() #max_power

0        74
1    103.52
2        78
3        90
4      88.2
Name: max_power, dtype: object

In [13]:
data[data['max_power']== 'bhp']# maxpower 변수에 bhp라는 문자가 있는지 확인

name  year  selling_price  km_driven fuel seller_type  \
4933  Maruti Omni CNG  2000          80000     100000  CNG  Individual   

     transmission         owner     mileage engine max_power torque  seats  \
4933       Manual  Second Owner  10.9 km/kg    796       bhp    NaN    8.0   

     max_power_unit  
4933           None

In [14]:
def isFloat(value): 
    try:
        num = float(value)
        return num
    except ValueError:
        return np.NaN

In [15]:
data['max_power'] = data['max_power'].apply(isFloat) # isFloat 함수 적용

In [16]:
data['max_power_unit'].unique() 

array(['bhp', nan, None], dtype=object)

In [17]:
data.drop ('max_power_unit', axis=1, inplace= True) # 변수 제거

In [18]:
# mileage 변수 전처리 하기

data[['mileage','mileage_unit']] = data['mileage'].str.split(expand=True)

In [19]:
data['mileage'] = data['mileage'].astype('float32')

In [20]:
data['mileage_unit'].unique()

array(['kmpl', 'km/kg', nan], dtype=object)

In [21]:
data['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [22]:
def mile(x):
    if x['fuel'] == 'petrol':
        return x['mileage'] / 80.43
    elif x['fuel'] == 'Diesel':
        return x['mileage'] / 73.53
    elif x['fuel'] == 'LPG':
        return x['mileage'] / 40.85
    else:
        return x['mileage'] / 44.23

In [23]:
data['mileage'] = data.apply(mile,axis=1)

In [24]:
data.drop('mileage_unit',axis=1,inplace=True)

In [25]:
# torque 변수 전처리하기
data['torque'].head()

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: object

In [26]:
data['torque']= data['torque'].str.upper() # torque 변수 대문자로 변환

In [27]:
def torque_unit(x):
    if 'NM' in str(x):
        return 'Nm'
    elif 'KGM'in str(x):
        return 'kgm'

In [28]:
data['torque_unit']= data['torque'].apply(torque_unit)
# torque 변수를 torque_unit 함수에 적용하여 torque_unit 이라는 변수로 저장

In [29]:
data['torque_unit'].unique()

array(['Nm', 'kgm', None], dtype=object)

In [30]:
data['torque_unit'].isna()
data[data['torque_unit'].isna()]
data[data['torque_unit'].isna()]['torque'].unique()

array([nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800',
       '210 / 1900'], dtype=object)

In [31]:
data['torque_unit'].fillna('Nm', inplace=True) #결측치를 Nm으로 대체

In [32]:
string_example = '12.7@ 2,700(KGM@ RPM)'

In [33]:
string_example[:4] # 4번째 자리 전까지 인덱싱

'12.7'

In [34]:
for i, j in enumerate(string_example):
    print(i, '번째 텍스트:',j)

0 번째 텍스트: 1
1 번째 텍스트: 2
2 번째 텍스트: .
3 번째 텍스트: 7
4 번째 텍스트: @
5 번째 텍스트:  
6 번째 텍스트: 2
7 번째 텍스트: ,
8 번째 텍스트: 7
9 번째 텍스트: 0
10 번째 텍스트: 0
11 번째 텍스트: (
12 번째 텍스트: K
13 번째 텍스트: G
14 번째 텍스트: M
15 번째 텍스트: @
16 번째 텍스트:  
17 번째 텍스트: R
18 번째 텍스트: P
19 번째 텍스트: M
20 번째 텍스트: )


In [35]:
for i,j in enumerate(string_example):
    if j not in '0123456789.':
        cut= i
        break

In [36]:
def split_num(x):
    x= str(x)
    for i,j in enumerate(x):
        if j not in '0123456789.':
            cut= i
            break
    return x[:cut]

In [37]:
data['torque'] = data['torque'].apply(split_num)

In [38]:
data['torque']

0         190
1         250
2        12.7
3        22.4
4        11.5
        ...  
8123    113.7
8124       24
8125      190
8126      140
8127      140
Name: torque, Length: 8128, dtype: object

In [39]:
data['torque'] = data['torque'].replace('',np.NaN)


In [40]:
data['torque'] = data['torque'].astype('float64')


In [41]:
data['torque'].head()

0    190.0
1    250.0
2     12.7
3     22.4
4     11.5
Name: torque, dtype: float64

In [42]:
def torque_trans(x):
    if x['torque_unit']=='kgm':
        return x['torque']*9.8066 # kgm*9.8066 = Nm
    else:
        return x['torque']

In [43]:
data['torque']= data.apply(torque_trans,axis=1)

In [44]:
data.drop('torque_unit',axis=1, inplace=True)

In [45]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage engine  max_power  \
0  Individual       Manual   First Owner  0.318237   1248      74.00   
1  Individual       Manual  Second Owner  0.287502   1498     103.52   
2  Individual       Manual   Third Owner  0.400181   1497      78.00   
3  Individual       Manual   First Owner  0.312797   1396      90.00   
4  Individual       Manual   First Owner  0.364006   1298      88.20   

      torque  seats  
0  190.00000    5.0  
1  250.00000    5.0  
2  124.54382    5.0  
3  219.66784    5.0  
4  112.77590    5.0

In [46]:
# name 변수 전처리 하기 
data['name'] = data['name'].str.split(expand=True)[0]

In [47]:
data['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [48]:
data['name'] = data['name'].replace('Land','Land Rover')

In [49]:
# 전처리: 결측치 처리와 더미 변수 변환
data.isna().mean() #결측치 있는 항복 확인 가능

name             0.000000
year             0.000000
selling_price    0.000000
km_driven        0.000000
fuel             0.000000
seller_type      0.000000
transmission     0.000000
owner            0.000000
mileage          0.027190
engine           0.027190
max_power        0.026575
torque           0.027313
seats            0.027190
dtype: float64

In [50]:
data.dropna(inplace = True)
len(data)

7906

In [51]:
data = pd.get_dummies(data, columns=['name', 'fuel', 'seller_type', 'transmission', 'owner'], drop_first=True).astype(int)


In [52]:
data.head()

year  selling_price  km_driven  mileage  engine  max_power  torque  seats  \
0  2014         450000     145500        0    1248         74     190      5   
1  2014         370000     120000        0    1498        103     250      5   
2  2006         158000     140000        0    1497         78     124      5   
3  2010         225000     127000        0    1396         90     219      5   
4  2007         130000     120000        0    1298         88     112      5   

   name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0           0          0  ...            1         0            0   
1           0          0  ...            1         0            0   
2           0          0  ...            0         0            1   
3           0          0  ...            1         0            0   
4           0          0  ...            0         0            1   

   seller_type_Individual  seller_type_Trustmark Dealer  transmission_Manual  \
0                       1                             0                    1   
1                       1                             0                    1   
2                       1                             0                    1   
3                       1                             0                    1   
4                       1                             0                    1   

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                           0                   0                     0   
1                           0                   1                     0   
2                           0                   0                     0   
3                           0                   0                     0   
4                           0                   0                     0   

   owner_Third Owner  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  

[5 rows x 48 columns]

In [53]:
#모델및 평가하기 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.drop('selling_price',axis=1), data['selling_price'], test_size=0.2, random_state=100)

In [54]:

from sklearn.ensemble import RandomForestRegressor

In [55]:
model =  RandomForestRegressor(random_state=100) # 모델 객체 생성

model.fit(X_train,y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [56]:

model.fit(X_train,y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [57]:
from sklearn.metrics import mean_squared_error
print("train_rmse:", mean_squared_error(y_train,train_pred)**0.5,
     "test_rmse:", mean_squared_error(y_test,test_pred)**0.5)

train_rmse: 56958.228011854255 test_rmse: 135276.54192172986


In [58]:
from sklearn.model_selection import KFold

In [59]:
data

year  selling_price  km_driven  mileage  engine  max_power  torque  \
0     2014         450000     145500        0    1248         74     190   
1     2014         370000     120000        0    1498        103     250   
2     2006         158000     140000        0    1497         78     124   
3     2010         225000     127000        0    1396         90     219   
4     2007         130000     120000        0    1298         88     112   
...    ...            ...        ...      ...     ...        ...     ...   
8123  2013         320000     110000        0    1197         82     113   
8124  2007         135000     119000        0    1493        110     235   
8125  2009         382000     120000        0    1248         73     190   
8126  2013         290000      25000        0    1396         70     140   
8127  2013         290000      25000        0    1396         70     140   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0         5           0          0  ...            1         0            0   
1         5           0          0  ...            1         0            0   
2         5           0          0  ...            0         0            1   
3         5           0          0  ...            1         0            0   
4         5           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
8123      5           0          0  ...            0         0            1   
8124      5           0          0  ...            1         0            0   
8125      5           0          0  ...            1         0            0   
8126      5           0          0  ...            1         0            0   
8127      5           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
8123                       1                             0   
8124                       1                             0   
8125                       1                             0   
8126                       1                             0   
8127                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
8123                    1                           0                   0   
8124                    1                           1                   0   
8125                    1                           0                   0   
8126                    1                           0                   0   
8127                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
8123                     0                  0  
8124                     0                  0  
8125                     0                

In [60]:
data.reset_index(drop=True, inplace=True)

In [61]:
data

year  selling_price  km_driven  mileage  engine  max_power  torque  \
0     2014         450000     145500        0    1248         74     190   
1     2014         370000     120000        0    1498        103     250   
2     2006         158000     140000        0    1497         78     124   
3     2010         225000     127000        0    1396         90     219   
4     2007         130000     120000        0    1298         88     112   
...    ...            ...        ...      ...     ...        ...     ...   
7901  2013         320000     110000        0    1197         82     113   
7902  2007         135000     119000        0    1493        110     235   
7903  2009         382000     120000        0    1248         73     190   
7904  2013         290000      25000        0    1396         70     140   
7905  2013         290000      25000        0    1396         70     140   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0         5           0          0  ...            1         0            0   
1         5           0          0  ...            1         0            0   
2         5           0          0  ...            0         0            1   
3         5           0          0  ...            1         0            0   
4         5           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
7901      5           0          0  ...            0         0            1   
7902      5           0          0  ...            1         0            0   
7903      5           0          0  ...            1         0            0   
7904      5           0          0  ...            1         0            0   
7905      5           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
7901                       1                             0   
7902                       1                             0   
7903                       1                             0   
7904                       1                             0   
7905                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
7901                    1                           0                   0   
7902                    1                           1                   0   
7903                    1                           0                   0   
7904                    1                           0                   0   
7905                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
7901                     0                  0  
7902                     0                  0  
7903                     0                

In [62]:
kf = KFold(n_splits=5)

In [63]:
X= data.drop('selling_price', axis=1)
y= data['selling_price']

In [64]:
for i,j in kf.split(X):
    print(i,j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]


In [65]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index],X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [72]:
train_rmse_total = []  # ✅ 반복문 외부에서 리스트 초기화
test_rmse_total = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model = RandomForestRegressor(n_estimators=100, random_state=100)
    model.fit(X_train, y_train)
    
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_rmse = mean_squared_error(y_train, train_pred, squared=False)
    test_rmse = mean_squared_error(y_test, test_pred, squared=False)

    train_rmse_total.append(train_rmse) 
    test_rmse_total.append(test_rmse)


In [73]:
train_rmse_total

[53090.1837691973,
 60752.476865941244,
 59750.91028782172,
 58618.01013804103,
 61499.857073971856]

In [75]:
print("train-rmse:", sum(train_rmse_total)/5, "test_rmse_total:", sum(test_rmse_total)/5)

# 교차검증 사용하기 전과 약간의 차이가 보이며 전반적으로 RMSE가 더 올라간 모습이며 교차검증을 사용한 결과가 조금 더 정확하다

train-rmse: 58742.287626994636 test_rmse_total: 144826.15785806763
